Create profile
tanaka-naoto-40/mokumoku pull request #2
Opened 2023-07-02 12:49 UTC by tanaka-naoto-40

### 選択した事業課題
直近一年間で、2回以上もくもく会に参加してくれた人は利用者全体の1%のみ。もくもく会で気の合う仲間を見つけられなかったのではないか？
### テスト結果
[![Image from Gyazo](https://i.gyazo.com/0c3f9b79e494520a69156f87a10da75f.png)](https://gyazo.com/0c3f9b79e494520a69156f87a10da75f)

・テスト結果の2つのpendingは保留のテストと調べたのでこのまま提出します
・①提案編では、プロフィールにSNS等のURLを記載する欄を作ると書いたのですが
　頂いた実装方針にHobbyとProfileを登録とあったのでそちらに倣いました。

2023-07-02 23:00 UTC, busitora requested changes
一点コメントしました！

2023-07-02 23:00 UTC, busitora commented on app/models/user.rb
> +    followers.find_by(followed_id: user_id).destroy
followers.find_by(followed_id: user_id) が nil の場合の考慮もしましょう！

2023-07-03 04:41 UTC, tanaka-naoto-40 commented
>followers.find_by(followed_id: user_id) が nil の場合の考慮

nilだった場合 `.destroy`を実行すると `NoMethodError` が発生するので
`&.destroy' とすることでfollowersがnilの場合にエラーではなくnilを返すように対応しました

対応として正解かご確認お願いいたします。

2023-07-03 10:46 UTC, tarakish reviewed
修正良いと思います！LGTMです！

2023-07-04 03:18 UTC, tanaka-naoto-40 commented
ありがとうございます！

2023-07-04 03:19 UTC, closed without merging